
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.Normalizer;
import java.util.logging.Level;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import jdk.nashorn.internal.scripts.JO;
import java.util.logging.Logger;







public class projekjavaapp extends javax.swing.JFrame {
    
    
    public projekjavaapp() {
        initComponents();
        Tampilkan_Data();
    }
        
    private Connection conn = new Koneksi().Connect();
    private DefaultTableModel tabmodel;
            
    public int Total_Harga;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        layout = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txt_bayar = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        combo_jenis = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        txt_harga = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txt_berat = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txt_tlharga = new javax.swing.JTextField();
        btn_logout = new javax.swing.JButton();
        btn_transaksi = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabel_data = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();
        btn_batal1 = new javax.swing.JButton();

        jLabel4.setText("HARGA");

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        layout.setBackground(java.awt.Color.green);
        layout.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("MyLaundry");
        jLabel1.setToolTipText("");
        jLabel1.setBorder(new javax.swing.border.MatteBorder(null));
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabel1.setOpaque(true);
        layout.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 20, 170, 80));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("BAYAR");
        jLabel2.setToolTipText("");
        layout.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 320, 80, 40));

        txt_bayar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_bayarActionPerformed(evt);
            }
        });
        layout.add(txt_bayar, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 330, 170, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Data Laundry");
        jLabel3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabel3.setOpaque(true);
        layout.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 100, 390, 40));

        combo_jenis.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "PILIH JENIS", "CUCI BIASA", "CUCI SEHARI JADI", "CUCI ANTAR JEMPUT", "CUCI KHUSUS" }));
        combo_jenis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combo_jenisActionPerformed(evt);
            }
        });
        layout.add(combo_jenis, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 130, 170, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("HARGA");
        layout.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, 60, 40));

        txt_harga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_hargaActionPerformed(evt);
            }
        });
        layout.add(txt_harga, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 180, 170, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("BERAT");
        layout.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, 80, 40));

        txt_berat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_beratActionPerformed(evt);
            }
        });
        txt_berat.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_beratKeyReleased(evt);
            }
        });
        layout.add(txt_berat, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 230, 170, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("TOTAL HARGA");
        jLabel7.setToolTipText("");
        layout.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 270, 130, 40));

        txt_tlharga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_tlhargaActionPerformed(evt);
            }
        });
        layout.add(txt_tlharga, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 280, 170, -1));

        btn_logout.setText("Logout");
        btn_logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_logoutActionPerformed(evt);
            }
        });
        layout.add(btn_logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 390, 110, 60));

        btn_transaksi.setText("BAYAR");
        btn_transaksi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_transaksiActionPerformed(evt);
            }
        });
        layout.add(btn_transaksi, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 390, 110, 60));

        tabel_data.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tabel_data);

        layout.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 150, 390, 220));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("JENIS CUCI");
        jLabel8.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        layout.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, 100, 40));

        btn_batal1.setText("BATAL");
        btn_batal1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_batal1ActionPerformed(evt);
            }
        });
        layout.add(btn_batal1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 390, 110, 60));

        getContentPane().add(layout);
        layout.setBounds(20, 20, 770, 480);

        setSize(new java.awt.Dimension(825, 551));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    public void reset(){
        combo_jenis.setSelectedItem("PILIH JENIS");
        txt_harga.setText("");
        txt_berat.setText("");
        txt_tlharga.setText("");
        txt_bayar.setText("");
    }
        
    public void Tampilkan_Data(){
        String[] Data = {"Jenis Cuci","Harga/Kilo","Berat","Total harga",};
        tabmodel = new DefaultTableModel(null, Data);
        tabel_data.setModel(tabmodel);
        String sql= "Select*from data_laundry";
        try {
            Statement stat = conn.createStatement();
            ResultSet hasil = stat.executeQuery(sql);
            while (hasil.next()) {
                   String JenisCuci = hasil.getString("jenis_cuci");
                   String Harga = hasil.getString("harga");
                   String Berat = hasil.getString("berat");
                   String TotalHarga = hasil.getString("total_harga");
                   String[] DataLaundry = {JenisCuci,Harga,Berat,TotalHarga};
                   tabmodel.addRow(DataLaundry);
            }
        } catch (SQLException ex) {
            Logger.getLogger(Normalizer.Form.class.getName()).log(Level.SEVERE, null, ex);                              
        }
    }

    private void txt_bayarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_bayarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_bayarActionPerformed

    private void txt_hargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_hargaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_hargaActionPerformed

    private void txt_beratActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_beratActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_beratActionPerformed

    private void txt_tlhargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_tlhargaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_tlhargaActionPerformed

    private void btn_logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_logoutActionPerformed
    new LoginPage().setVisible(true);
    this.setVisible(false);
    }//GEN-LAST:event_btn_logoutActionPerformed

    private void btn_transaksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_transaksiActionPerformed
        String url = "Insert into data_laundry values(?,?,?,?,?,?)";
        if(txt_harga.getText().isEmpty() || txt_berat.getText().isEmpty() || txt_tlharga.getText().isEmpty() || txt_bayar.getText().isEmpty()){ 
}else{
    int bayar = Integer.parseInt(txt_bayar.getText());
    int kembalian = bayar - Total_Harga;    
            try {
                PreparedStatement stat = conn.prepareStatement(url);
                stat.setString(1, String.valueOf(combo_jenis.getSelectedItem()));
                stat.setString(2, txt_harga.getText());
                stat.setString(3, txt_berat.getText());
                stat.setString(4, txt_tlharga.getText());
                stat.setString(5, txt_bayar.getText());
                stat.setString(6, String.valueOf(kembalian));
                stat.executeUpdate();
                JOptionPane.showMessageDialog(null, "KEMBALIAN :\n"+kembalian);
            } catch (SQLException e) {
                JOptionPane.showMessageDialog(null, "Transaksi Gagal"+e);
            }
    reset();
    Tampilkan_Data();
    
}      
    }//GEN-LAST:event_btn_transaksiActionPerformed

    
    private void combo_jenisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combo_jenisActionPerformed
        if(combo_jenis.getSelectedItem().equals("PILIH JENIS")){
            txt_harga.setText("0");
        }else if(combo_jenis.getSelectedItem().equals("CUCI BIASA")){
            txt_harga.setText("10000");
        }else if(combo_jenis.getSelectedItem().equals("CUCI SEHARI JADI")){
            txt_harga.setText("20000");
        }else if(combo_jenis.getSelectedItem().equals("CUCI ANTAR JEMPUT")){
            txt_harga.setText("50000");
        }else if(combo_jenis.getSelectedItem().equals("CUCI KHUSUS")){
            txt_harga.setText("100000");
        }
    }//GEN-LAST:event_combo_jenisActionPerformed

    private void txt_beratKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_beratKeyReleased
        if(txt_berat.getText().equals("")){
            txt_tlharga.setText("0");
        }else{
            int harga = Integer.parseInt(txt_harga.getText());
            int berat = Integer.parseInt(txt_berat.getText());
            Total_Harga = harga*berat;
            txt_tlharga.setText(String.valueOf(Total_Harga));
        }
    }//GEN-LAST:event_txt_beratKeyReleased

    private void btn_batal1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_batal1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_batal1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(projekjavaapp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(projekjavaapp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(projekjavaapp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(projekjavaapp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new projekjavaapp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_batal1;
    private javax.swing.JButton btn_logout;
    private javax.swing.JButton btn_transaksi;
    private javax.swing.JComboBox<String> combo_jenis;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel layout;
    private javax.swing.JTable tabel_data;
    private javax.swing.JTextField txt_bayar;
    private javax.swing.JTextField txt_berat;
    private javax.swing.JTextField txt_harga;
    private javax.swing.JTextField txt_tlharga;
    // End of variables declaration//GEN-END:variables
}
